using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace RealEstateAgency.View
{
    /// <summary>
    /// Логика взаимодействия для AccessWindow.xaml
    /// </summary>
    public partial class AccessWindow : Window
    {
        public AccessWindow()
        {
            InitializeComponent();
        }

        private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.Column.Header.ToString() == "Function" || e.Column.Header.ToString() == "Id")
                e.Cancel = true;
            LoginGrid.CellStyle = TryFindResource("CellCenter") as Style;
            LoginGrid.ColumnHeaderStyle = TryFindResource("HeaderCenter") as Style;
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            if (grid.Items.Count > 0)
                foreach (var item in grid.Columns)
                    if (item.Header.ToString() == "Admin rights")
                    {
                        item.DisplayIndex = 2;
                        break;
                    }
        }
    }
}
