using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace RealEstateAgency.View
{
    /// <summary>
    /// Логика взаимодействия для EditWindow.xaml
    /// </summary>
    public partial class EditWindow : Window
    {
        public EditWindow()
        {
            InitializeComponent();
        }

        private void TransactionData_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            string header = e.Column.Header.ToString();
            if (header == "Image" || header == "ClientSaleId" || header == "EmployeeId" || header == "TypeTransaction")
                e.Cancel = true;
        }

        private void TransactionData_AutoGeneratedColumns(object sender, EventArgs e)
        {
            var grid = (DataGrid)sender;
            if (grid.Items.Count > 0)
                foreach (var item in grid.Columns)
                {
                    if (item.Header.ToString() == "EmployeeId")
                    {
                        item.DisplayIndex = 5;
                        continue;
                    }
                    if (item.Header.ToString() == "ClientSaleId")
                    {
                        item.DisplayIndex = 5;
                        continue;
                    }
                    if (item.Header.ToString() == "Transaction")
                    {
                        item.DisplayIndex = 5;
                        continue;
                    }
                    if (item.Header.ToString() == "Photo")
                    {
                        item.DisplayIndex = 0;
                        continue;
                    }
                }
        }

        private void OfficeEmployeeData_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            string header = e.Column.Header.ToString();
            if (header == "OfficeId" || header == "EmployeeId")
                e.Cancel = true;

        }

    }
}
